# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6579d0f447ca14edf54d046f3bde7cb65096097967d5afc5e914a171429540e68f68dbab15bec794ca62c33f5369d40eeed187613428b87daaea5e2a9c652316

test:
  secret_key_base: 91fe4c38dae9e688e7bd17b03b21a4262f9c455ab71d0079199c08e5c4c6478da9e9d9f1b48296fd76410c4548484b2a241d92b70d0008561373e69844d58e64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
